### ISSUE TITLE
Is there an Admin Console?

### ISSUE THREAD

**Issue by arindammitra06** [ddlogesh/zinger-framework#10]
First of all.. Thanks for building such a wonderful platform. We plan to utilize the same in our project.

But I was wondering if there is an admin console that's already developed or under development, it would be great.

Please let me know. Thanks.

**Comment by harshavardhan98** [comment]
Hi Arindam Mitra ,

Thanks for the kind words.

We are currently working on the admin console. We are doing a complete refactor and working on new features too so I will not be able to give a due date when it would be completed. 

But all the admin API's are available. You can directly use it from tools like Postman. 

For further doubts and clarifications join our zinger discord group -  https://discord.com/invite/TqADaXV

Thanks and Regards,
P.Harshavardhan

**Comment by arindammitra06** [comment]
Thank You. Would surely follow this repository and wait for the new features.. specially the admin console. 

Regards,
Arindam

**Comment by harshavardhan98** [comment]
I will update you when we release the admin console. Closing the issue.
