### ISSUE TITLE
Need to create an app

### ISSUE THREAD

**Issue by prineee** [ddlogesh/zinger-framework#6]
I want to create an app which is similar to swiggy, the only thing change is swiggy is the paleform of food ordering system whereas my creation will be of "used book ordering system".
Here every aspect of swiggy will be same, only in place of restaurants there will be book seller.
Remaining like in place of food menu there will; be books name and details.
Kindly any one can help me to finish this project.
thank you.

**Comment by MohammedJeseem** [comment]
Hi @prineee 
Im intrested to join with u

**Comment by prineee** [comment]
> Hi @prineee
> Im intrested to join with u

Most welcome haseen, but I am amature programr and need major help.

**Comment by MohammedJeseem** [comment]
Ok explain your requirements briefly

**Comment by prineee** [comment]
> Ok explain your requirements briefly

As I have explained that I need to develop an app through which a person can order used book just like in swiggy ordering the food with the help of menu but here in my app a person can order a book name in place of menu and that order will assigned to the rider and rider will collect the book from the particular shop and deliver to that client the payment may be e COD or prepaid
