### ISSUE TITLE
pom.xml Showing error when i load this in Eclipse

### ISSUE THREAD

**Issue by rajaspidey** [ddlogesh/zinger-framework#9]
when i try to import this project into Eclipse am getting some error in pom.xml file

![image](https://user-images.githubusercontent.com/1059186/91163745-aea56780-e6eb-11ea-8010-64b5cd8b81e7.png)

_sorry i dont know coding and just started learning so cant give you exact reason for the bug_

**Comment by ddlogesh** [comment]
There are many reasons for getting the error. Can you please share screenshot of Problems tab?
